spring.profiles.default=demo
server.port=${PORT:8181}

spring.jpa.show-sql=${JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}
spring.jpa.defer-datasource-initialization=true
spring.thymeleaf.cache=false
